version: '3.9'

services:
  mongo-data:
    container_name: mongo-data
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - safe-sender-mongodb-data:/data/db
    restart: always

  safe-sender-storage-api:
    build:
      context: .
      dockerfile: SafeSender.StorageAPI/Dockerfile
    ports:
      - "5006:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo-data
    restart: always

volumes:
  safe-sender-mongodb-data:
  
